{% set name = "solid" %}
{% set version = "5.66.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/solid-{{ version }}.tar.xz
  sha256: 78deab8c55c30f2c923795730a9655b4d05a75cd6240bc0caa64104b141a3a39

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('solid', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules
    - {{ cdt('libudev') }}  # [linux]
    - {{ cdt('libudev-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt
    - flex
    - bison

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5Solid.so

about:
  home: https://api.kde.org/frameworks/solid/html/index.html
  license: LGPL-v2.1-or-later
  license_family: GPL
  license_file: COPYING.LIB
  summary: 'Desktop hardware abstraction'
  description: |
    Solid is a device integration framework. It provides a way of querying
    and interacting with hardware independently of the underlying operating system.
  dev_url: https://cgit.kde.org/solid.git/tree

extra:
  recipe-maintainers:
    - scopatz
