{% set name = "solid" %}
{% set version = "5.79.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/solid-{{ version }}.tar.xz
  sha256: 34c3699100f117709f459adbe08c94562af387bf45a1901cbca0106cc4d07a0c

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('solid', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ version }}
    - {{ cdt('libudev') }}  # [linux]
    - {{ cdt('libudev-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt
    - flex
    - bison

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5Solid.so

about:
  home: https://api.kde.org/frameworks/solid/html/index.html
  license: BSD-3-Clause AND LGPL-2.0-only AND LGPL-2.1-only AND LGPL-2.1-or-later AND LGPL-3.0-only AND LicenseRef-KDE-Accepted-LGPL
  license_file:
    - LICENSES/BSD-3-Clause.txt
    - LICENSES/LGPL-2.0-only.txt
    - LICENSES/LGPL-2.1-only.txt
    - LICENSES/LGPL-2.1-or-later.txt
    - LICENSES/LGPL-3.0-only.txt
    - LICENSES/LicenseRef-KDE-Accepted-LGPL.txt
  summary: Desktop hardware abstraction
  description: |
    Solid is a device integration framework. It provides a way of querying
    and interacting with hardware independently of the underlying operating system.
  dev_url: https://cgit.kde.org/solid.git/tree

extra:
  recipe-maintainers:
    - scopatz
