travis:
  secure:
    BINSTAR_TOKEN: Uc04exCe8vISfLgCUaX42A06D65/8lpKGdbNG680IvWtwsZt4PjtPH9aV934OvYjLvF5eLFjTx4s7DBQ31r2lyzPMishFFLztbrvht9wECdT/12hIObdWuotulc6eqMSLPOhP99KOZtkqlmdHnESfBqZLM7n2mDjq/vW6JZ4gioyoEJyohIiOh6ZNwdqAoawfeNYEua2bhMRzhrEgIUB0ewrpYgOewr59IbaNydgRMr8egEF4NVfZ2GxvnwoIIq4nRYdzE8G31FsvuJw7hVz9cf/TrmzAzhv1ul41VQEnl2dJimLjNqoAs6oiMdKtaTn53hwzxBZIo+KK890kf8zbeEiVcNpDeU8gf0+IVihobNcQwSDJWHuDrZqO1mV8mcRJF74JfvfVOcMXUL6mFoNiTL8BZ1qXE57RyMRCMe00fcjo9RB9Up80gLo00NNocSxmB/9WknEzufym5lp05wnf7biq2C9ieBPhEpP/0ZZYhLJ0aRsknYu7wxtXWi6X3KSSBkqtAml7X9/ZTZTdCGY2YvX1MtB9YMWL6Yk0c0V2p4mzsXCU4nAIcjfs7rpk86joN+UjI+fOg4Py2h20DtIhp7xMH2zkws+zxfLBjGz2sYpIh5x69tE2IscdlRTkJFgJXgklg71DM1Ptg6uc2sd77YbsQV/BZHl5NefBGUrWAM=
conda_forge_output_validation: true
bot:
  check_solvable: True
  
